-- having
-- USED TO FILTER FROM GROUPS 
-- CANNOT DIRECTLY FILTER USING  AGGREGATE_FUNCTION NEED TO USE GROUP BY FIRST

-- EX

-- SELECT department, COUNT(*)
-- FROM employees
-- GROUP BY department
-- HAVING COUNT(*) > 3;